# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='estados',
            new_name='estado',
        ),
    ]
